# name: Ejecutar script Python

# on:
#   push:
#     branches:
#       - main

# jobs:
#   ejecutar-python:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Clonar repositorio
#         uses: actions/checkout@v3

#       - name: Configurar Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'

#       - name: Instalar dependencias
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Ejecutar script
#         run: python prueba.py

#       - name: Subir artefactos de ejecución
#         uses: actions/upload-artifact@v3
#         with:
#           name: reportes
#           path: |
#             reporte_ejecucion.csv
#             reporte_resultados.txt  


name: Construcción y prueba de paquete ROS 2 Humble

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar ROS 2 Humble
        run: |
          sudo apt update && sudo apt install -y curl gnupg2 lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | gpg --dearmor -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
          sudo apt update
          sudo apt install -y ros-humble-desktop python3-colcon-common-extensions python3-pip
          echo "source /opt/ros/humble/setup.bash" >> $GITHUB_ENV

      - name: Instalar dependencias de Python
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear workspace y construir
        run: |
          source /opt/ros/humble/setup.bash
          mkdir -p ~/ros2_ws/src
          cp -r $GITHUB_WORKSPACE/* ~/ros2_ws/src/
          cd ~/ros2_ws
          colcon build --symlink-install

      - name: Ejecutar pruebas
        run: |
          source /opt/ros/humble/setup.bash
          source ~/ros2_ws/install/setup.bash
          colcon test
